name:                Spinell
version:             0.1.0.0
github:              "githubuser/Spinell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Spinell#readme>

dependencies:
- base >= 4.7 && < 5
- hmatrix >= 0.19.0.0
- hmatrix-gsl >= 0.19.0.1
- hmatrix-tests
- hmatrix-special
- ad
- vinyl >= 0.10.0
- Frames
- microlens
- reflection
- Chart
- Chart-cairo
- Chart-gtk
library:
  source-dirs: src
executables:
  Spinell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Spinell

tests:
  Spinell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Spinell
